### ISSUE TITLE
Using oracle procedures via exec

### ISSUE THREAD

**Issue by ghost** [bchr02/node-oracledb#18]
Hi, i use driver on Windows Server 2k8 R2, how i can execute orecle procesures using `exec` syntax
like this?
`exec ASTRA.seg_cre_allvalues('ASTRA.CLIENTS','TYPEDOCCLI','CLIENTCODE');`

**Comment by bchr02** [comment]
Check out https://github.com/oracle/node-oracledb/tree/master/examples also I would suggest you post to https://github.com/oracle/node-oracledb/issues as it will get much more visibility.
